# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operacao', models.CharField(blank=True, choices=[('d', 'Debito'), ('c', 'Credito')], default='d', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('a', 'A Pagar'), ('p', 'Pago')], default='a', max_length=1)),
                ('descricao', models.TextField(blank=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Historico')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
            ],
            options={
                'ordering': ('-data_vencimento', 'valor'),
            },
        ),
    ]
