# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Conta')),
            ],
            bases=('financeiro.conta',),
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Conta')),
            ],
            bases=('financeiro.conta',),
        ),
    ]
