# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contapagar_contareceber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ContaPagar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagamentoRecebido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ContaReceber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
