# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_pagamentopago_pagamentorecebido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterModelOptions(
            name='contareceber',
            options={'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.AlterField(
            model_name='conta',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Aberta'), ('p', 'Paga')], default='a', max_length=1),
        ),
    ]
