# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operacao', models.CharField(blank=True, choices=[('d', 'Debito'), ('c', 'Credito')], default='d', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('a', 'Aberta'), ('p', 'Paga')], default='a', max_length=1)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-data_vencimento', 'valor'),
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='PagamentoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagamentoRecebido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Conta')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
            bases=('financeiro.conta',),
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Conta')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
            bases=('financeiro.conta',),
        ),
        migrations.AddField(
            model_name='conta',
            name='historico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Historico'),
        ),
        migrations.AddField(
            model_name='conta',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AddField(
            model_name='pagamentorecebido',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ContaReceber'),
        ),
        migrations.AddField(
            model_name='pagamentopago',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ContaPagar'),
        ),
    ]
