# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomepessoa', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenomepessoa', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='Cep')),
                ('tipologradouro', models.CharField(max_length=100, verbose_name='Tipo Logradouro')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'profissão',
                'verbose_name_plural': 'profissões',
            },
        ),
        migrations.CreateModel(
            name='ProfissoesPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissoesPessoa', to='core.Pessoa')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profissao')),
            ],
            options={
                'verbose_name': 'profissão da pessoa',
                'verbose_name_plural': 'profissao da pessoa',
            },
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Qualificação',
                'verbose_name_plural': 'Qualificações',
            },
        ),
        migrations.CreateModel(
            name='QualificacaoProfissoesPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacaoProfissoesPessoa', to='core.ProfissoesPessoa')),
                ('qualificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Qualificacao')),
            ],
            options={
                'verbose_name': 'qualificação da profissão da pessoa',
                'verbose_name_plural': 'qualificações das profissões da pessoa',
            },
        ),
        migrations.AlterUniqueTogether(
            name='qualificacaoprofissoespessoa',
            unique_together=set([('profissao', 'qualificacao')]),
        ),
        migrations.AlterUniqueTogether(
            name='profissoespessoa',
            unique_together=set([('pessoa', 'profissao')]),
        ),
    ]
