# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160317_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(max_length=10, null=True, verbose_name='Cep'),
        ),
    ]
