# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoa_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to=settings.AUTH_USER_MODEL),
        ),
    ]
