# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160325_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL),
        ),
    ]
